; CIP-0060: Music NFT Metadata Standard
; Version: 1.0.0

string = text .size (0..64)

music-token-details = {
    ; TBD
}

; CIP-0060: Music NFT Metadata Standard
; Version: 1.0.0
cip60-details = {
    ? 0 : string                ; version
    1 : music-token-details     ; CIP-0060 Music NFT Details
}