string = bstr .size (1..64) ; tstr / string from 1 up to 64 chars only

sig_256 = bstr .size (64..64) ; 256 bytes signature (256 / 64 = 4 bytes)

transaction_metadata = {
  1304: on-chain_metadata
}

on-chain_metadata = {
      subject: string
    , rootHash: sig_256
    , metadata: [+ string] / [+ string / [+ string]]
    , schemaVersion: uint
    , type: certify / audit
}

certify = {
      action: "CERTIFY" 
    , certificationLevel: 1 / 2 / 3 
    , certificateIssuer: string
}

audit = {
      action: "AUDIT" 
    , certificationLevel: 0 
    , certificateIssuer: string
}