name = "0102/onchain-reference"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project '0102/onchain-reference'"

[repository]
user = "0102"
project = "onchain-reference"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
