; CIP-XXXX: CIP-Descriptor
; Version: 1

; Define any common or reusable pieces such as strings, URIs, etc

string = text .size (0..64)

; Define any nested objects before the top-level object

royalty-object = {
  0: string       ; rate
  1: [+ string]   ; address
}

royalty-details-object = [* royalty-object]

; Define the top-level CIP object

cip-xxxx-details = {
  ? 0 : uint            ; optional version number
  1 : royalty-details-object  ; array containing zero (or more) royalty objects
}
